### ISSUE TITLE
What is "Alt+R B/O/F" referring to?

### ISSUE THREAD

**Issue by teunbruijnen** [newinnovations/remote-edit-ni#54]
I'm terribly sorry but I have no idea how to use the shortcut "Alt+R O" etc. 

What does ALT+R signify? It's not holding Alt & Ctrl at the same time. It's not holding Alt & fn at the same time. It's not holding Alt & windows key at the same time. It's not the Alt gr key. I don't know what it is supposed to be and googling doesn't help me. 

Since I am unable to change the shortcut, my last option is to ask here! Thanks for your time

**Comment by urban-1** [comment]
It has been a long time since I used this but Alt+R means:

- Press `Alt` (do not release)
- Press `r` (no need for shift+r, capitalization is wrong here)
- Release both keys and shortly after (do not leave a large time gap)
- Press one of `b` or `o` or `f` - each one does a different thing

Essentially, `Alt+r` acts as "escape sequence" for the next key-press

Now in Atom, if I remember, you should be able to edit all keys in some config file so you can change that behaviour if it does not suit you. I don't exactly remember where this config is but I think you can troubleshoot shortcuts with `Ctrl+.` which should start showing you what key combos are active as you type/press them

**Comment by teunbruijnen** [comment]
You're a hero @urban-1 ! I never thought about "escape sequence" shortcut type things. That opens up a whole new world of shortcuts.

Thanks for the answer and tips, awesome!!
